version: '3.9'
name: advent
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - .././.postgres/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d Advent -U admin']
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Advent
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - internal

networks:
  internal:
    name: advent-network
